# variable_definitions.py

# Label mapping for better readability
label_mapping = {
    # Core variables from original mapping
    'b_sk_n_digital': 'Digital Skills Needed',
    'b_sk_n_man': 'Mgmt Skills Needed',
    'roi4': 'Negative ROI',
    'roi_yes': 'ROI Measured',
    'ecp_extredeployment': 'External Redeployment',
    'p_effect_reverse': 'Program Effectiveness',
    'evp_network': 'Cross-departmental Networks',
    'roi5': 'Positive ROI',
    'sum_tr_sk': 'Sum of Trained Skills',
    'sha_b_sk_n_digital': 'Share Needed Digital Skills',
    'stat_government': 'Help Org Use Gov Subsidy',
    'ecp_intredeployment': 'Internal Redeployment',
    'stat_csr': 'Fulfilling CSR Requirement',
    'reason_dei': 'Reason DEI',
    'sk_selected': 'Total Nr skills needed',
    'stand2': 'Mix Standardization customization',
    'f_union_1_-_25%': 'Union Share 1-25%',
    'inc_mgr_nofin': 'Manager: Non-financial Incentive',
    'invest_cont': 'Continued Investment',
    'p_fund_gov': 'Funded by Government',
    'f_medium': 'Medium Firm Size (100-999)',
    'roi2': 'Not yet but intend to calculate ROI',
    'roi3': 'Tried to but unable to',
    'roi1': 'No attempt to calculate',
    'p_eligibility': 'Participation Eligibility',
    'p_targetfunc_it_Not_Selected': 'Target Function: IT not selected',
    'p_cont_investment_Very likely': 'Cont. Investment Very Likely',
    'p_adv_hr': 'Advocate HR',
    'p_participated_2023_1000 - 9999': 'Participated in 2023 (1000 - 9999)',
    'p_program_length': 'Program Length (Years)',
    'p_fund_org': 'Funded by Org',
    'p_criteria_jobtitle': 'Selection Criteria: Job Title',
    'p_criteria_assmskills': 'Selection Criteria: Assessment of Skills',
    'p_target_emp': 'Target Group: Employees',
    'p_challenge_progcompl': 'Challenge: Program Completion',
    'p_year_end_2023': 'Program End: 2023',
    'p_part': 'Number of participants',
    'p_fund_wrk': 'Funded by Worker',
    'sha_b_sk_n_soft': 'Needed share soft skill',
    'sha_b_sk_n_man': 'Needed share mgmt skill',
    'p_part_exp': 'Expected Participation',
    'tot_kpi_tracked': 'Total Nr of KPIs',
    'f_union_1___25%': 'Union share 1-25%',
    'p_targetfunc_it': 'Target function IT',
    'inc_wrk_cert': 'Worker Incentive - Certificate or Badge',
    'k_track_attract': 'Whether program attracted right participants',
    'k_review_bul': 'KPI review by Unit/Function Leaders',
    'p_fund_union': 'Funded by Union',
    
    # Additional firm/organization variables
    'size': 'Q1_2: How many people does your organization employ?',
    'm_tenure_firm': 'Tenure of Respondent',
    'noanswerQ5_27_n1': 'How was this upskilling program funded?: I don\'t know - No Answer',
    'noanswerQ7_29_n1': 'How was this reskilling program funded?: I don\'t know - No Answer',
    'f_naics': 'Firm: 2 digits NAICS industry',
    'HP_region4': 'Hidden Question. Region4',
    'HP_region9': 'Hidden Question. Region9',
    'f_size_n': 'Firm Size (Numeric)',
    'f_size': 'RECODE of f_size_n',
    'f_geography': 'Firm: Where do majority of employees work',
    'f_geography_grouped': 'Geography - grouped',
    'f_hq': 'Firm: HQ location',
    'f_mne': 'Firm: MNE dummy',
    'f_sub_number': 'Firm: Number of continents firm is active in',
    'f_export': 'Firm: Dummy if firm exports',
    'f_own': 'Firm: Ownership',
    'f_naics_clone': 'Firm: 2 digits NAICS industry',
    'f_naics_super': 'Superindustry',
    'f_naics_super2': 'Superindustry 2',
    'f_union': 'Firm: Union %',
    'f_public': 'Firm: Dummy publicly listed',
    'f_subsidy': 'Firm: Utilized a subsidy for initiatives',
    'f_large': 'Large Firm Size (1000+)',
    'f_union50': 'Firm: Union share over 50%',
    'fsub': 'Firm has subsidies',
    
    # Role and HR variables
    'program': 'Program type',
    'm_role': 'Role of Respondent',
    'hr_workforce': 'D: Engagement in Workforce activity',
    'hr_sk_description': 'D: Skill taxonomy needed to perform in given occupation',
    'hr_sk_inventory_use': 'D: How useful is the inventory of skills for workforce planning activities?',
    'hr_academy': 'D: Investment in setting up academy/school',
    'hr_internalmkt': 'D: advertised to specific employees and no permission needed',
    
    # Program-specific variables
    'p_participated': 'Program: Number of people who have participated since inception',
    'p_participated_2023': 'Program: Number of people who will have participated end of 2023',
    'p_mandavolunt': 'Was the program mandatory or opt-in for majority?',
    'p_year_start': 'Program Start Year',
    'p_year_end': 'Program End Year',
    'p_hourstrained': 'Total hours trained (per employee)',
    'p_duration': 'Duration of program',
    'p_comphours': 'Program during working hours',
    'p_otjactivities': 'On-the-job activities included',
    'p_cost': 'Estimated cost per person',
    'p_adequatefund': 'Was the program adequately funded?',
    'p_adequatefunddummy': 'Adequately funded Dummy',
    'p_fund_other': 'Other funding source',
    'p_advocacy': 'Who is the primary advocate for investments in the program?',
    'p_responsibility': 'Who has the primary responsibility to implement the program?',
    'p_application': 'Who could apply?',
    'p_selection': 'Were participants selected by org?',
    'p_criteria_tenure': 'Criteria - Tenure',
    'p_criteria_qualifications': 'Criteria - Pre-existing skills/qualifications',
    'p_criteria_assmsmotivation': 'Criteria - Pre-assessment of motivation',
    'p_criteria_managerrec': 'Criteria - Manager\'s recommendation',
    'p_criteria_other': 'Criteria - Other',
    'p_targetemp_c': 'Target - C-suite',
    'p_targetemp_bul': 'Target - Unit Leaders',
    'p_targetemp_mm': 'Target - Middle Managers',
    'p_targetemp_emp': 'Target - Employees',
    'p_targetfunc_leg': 'Target - Legal',
    'p_targetfunc_hr': 'Target - HR',
    'p_targetfunc_adm': 'Target - Administration',
    'p_targetfunc_op': 'Target - Operations/Manufacturing',
    'p_targetfunc_mrksal': 'Target - Marketing/Sales',
    'p_targetfunc_rd': 'Target - Research/Development',
    'p_targetfunc_accfin': 'Target - Accounting/Finance',
    'p_targetfunc_cust': 'Target - Customer Service',
    'p_difloc': 'Was the program rolled out in different locations',
    'p_difstand': 'Was the program standardized across locations',
    'p_ongoing': 'Program is ongoing',
    'p_long': 'Program is long-term',
    'p_hours_long': 'Program has many training hours',
    'p_oja': 'On-job activities indicator',
    'p_compfull': 'Program fully compensated',
    'p_target_top': 'Program targets top management',
    'p_target_middle': 'Program targets middle management',
    'p_target_topmiddle': 'Program targets top and middle management',
    'p_target_middleemp': 'Program targets middle management and employees',
    'p_target_all': 'Program targets all levels',
    'p_target_topbottom': 'Program targets top management and employees',
    
    # Challenge variables
    'p_challenge_convincingemployees': 'Challenge - Convincing eligible employees to apply',
    'p_challenge_selecting': 'Challenge - Selecting the right participants',
    'p_challenge_learning': 'Challenge - Ensuring that participants learned new skills',
    'p_challenge_convmanager': 'Challenge - Convincing managers to allow their employees to participate',
    'p_challenge_linkprogramcareer': 'Challenge - Linking the program to career progressions',
    'p_challenge_effectiveness': 'Challenge - Monitoring the effectiveness of the program',
    'p_challenge_scaling': 'Challenge - Scaling-up the program',
    'p_challenge_determreturn': 'Challenge - Determining financial returns of programs relative to other policies',
    'p_challenge_supportoutsideHR': 'Challenge - Getting the support of other corporate managers outside HR',
    'p_challenge_funding': 'Challenge - Finding adequate resources to fund the program',
    'p_challenge_other': 'Challenge - Other',
    'p_cha_takeup': 'Challenge - Program takeup',
    'p_cha_during': 'Challenge - During program',
    'p_cha_support': 'Challenge - Program support',
    'p_cha_scale': 'Challenge - Program scaling',
    
    # Design and delivery variables
    'dd_pilot_length': 'Length of pilot/experimental phase (or none)',
    'dd_pilot_dummy': 'Pilot Dummy variable',
    'dd_pilot_ct': 'Did the pilot have control/treatment?',
    'dd_pilot_over': 'Is experiment/pilot over?',
    'dd_design_board': 'Design - Board of Directors',
    'dd_design_c': 'Design - C-Suite Leaders',
    'dd_design_hr': 'Design - HR Leaders',
    'dd_design_bul': 'Design - Unit/Function Leaders',
    'dd_design_mm': 'Design - Middle Managers',
    'dd_design_emp': 'Design - Employees',
    'dd_design_union': 'Design - Unions',
    'dd_design_ia': 'Design - Internal Academy',
    'dd_design_top': 'Design - Top Management',
    'dd_external': 'Were external parties involved?',
    'dd_extdesign_ta': 'External Designer - Trade Association',
    'dd_extdesign_gov': 'External Designer - Government',
    'dd_extdesign_acad': 'External Designer - Academic Institutions',
    'dd_extdesign_lsshelf': 'External Designer - Learning Specialist (Off-the-Shelf)',
    'dd_extdesign_custom': 'External Designer - Learning Specialist (Custom)',
    'dd_extdesign_all': 'External Designers - Combined Categories',
    'dd_delivery': 'Delivery - Who delivered the program?',
    
    # Motivation variables
    'mot_mgr': 'Difficulty to get managers to support',
    'mot_wrk': 'Difficulty to get employees to enroll',
    'mot_mgragg': 'Difficulty to get managers to support (aggregated)',
    'mot_wrkagg': 'Difficulty to get employees to enroll (aggregated)',
    
    # Incentive variables
    'inc_mgr_fin': 'Manager Incentive - Financial',
    'inc_mgr_rec': 'Manager Incentive - Other Form of Recognition',
    'inc_mgr_intrin': 'Manager Incentive - Intrinsic',
    'inc_mgr_none': 'Manager Incentive - No Incentive',
    'inc_mgr_all': 'Manager Incentive - Combined Incentive Categories',
    'inc_wrk_career': 'Worker Incentive - Informed of Career Benefit',
    'inc_wrk_risk': 'Worker Incentive - Informed of Risk',
    'inc_wrk_fin': 'Worker Incentive - Financial Incentive',
    'inc_wrk_nofin': 'Worker Incentive - Non-Financial Incentive',
    'inc_wrk_rec': 'Worker Incentive - Other Form of Recognition',
    'inc_wrk_strat': 'Worker Incentive - Informed of Strategic Importance',
    'inc_wrk_job': 'Worker Incentive - Job Offer',
    'inc_wrk_all': 'Worker Incentive - Combined Categories',
    'inc_man1': 'Manager Incentive - No Incentive (group)',
    'inc_man2': 'Manager Incentive - Non-financial (group)',
    'inc_man3': 'Manager Incentive - Financial (group)',
    'inc_man_fin': 'Manager Incentive - Financial (indicator)',
    'inc_emp1': 'Worker Incentive - Non-financial (group)',
    'inc_emp2': 'Worker Incentive - Badge or Certificate (group)',
    'inc_emp3': 'Worker Incentive - Financial (group)',
    'inc_emp4': 'Worker Incentive - Job Offer (group)',
    'inc_emp_fin': 'Worker Incentive - Financial (indicator)',
    
    # Tracking and KPI variables
    'exp_participation': 'Were expectation about participation met?',
    'p_finassessment': 'Final assessment to assess whether skills improved',
    'k_track_numberppl': 'How many ppl started program',
    'k_track_hours': 'Total hours completed',
    'k_track_completion': 'How many people completed program',
    'k_track_changeskill': 'Whether participants saw change in skill set',
    'k_track_changecareer': 'Change in career trajectory/moved to different role',
    'k_track_otherHR': 'Other HR related outcomes (e.g., reduced attrition)',
    'k_track_busoutcomes': 'Business Outcomes',
    'k_track_benefitstraining': 'Benefits vs. alternative approaches',
    'k_track_other': 'Other KPI tracked',
    'k_track_none': 'We did not track any of these metrics',
    'k_review_BoD': 'Review - Board of Directors',
    'k_review_c': 'Review - C-Suite Leaders',
    'k_review_hr': 'Review - HR Leaders',
    'k_review_mm': 'Review - Middle Managers',
    'k_review_emp': 'Review - Employees',
    'k_review_union': 'Review - Unions',
    'k_review_ia': 'Review - Internal Academy',
    'k_review_other': 'Review - Other',
    'k_reviewcombined_c': 'Review - Board of Directors + C-Suite',
    'k_reviewcombined_hr': 'Review - HR Leaders',
    'k_reviewcombined_others': 'Review - Others',
    'k_freq': 'How often were the KPIs reviewed?',
    'kpi_input': 'KPI focused on input metrics',
    'kpi_output_micro': 'KPI focused on micro output metrics',
    'kpi_output_macro': 'KPI focused on macro output metrics',
    'kpiinput1': 'No KPI input metrics',
    'kpiinput2': 'Has KPI input metrics',
    'kpioutput_micro1': 'No KPI micro output metrics',
    'kpioutput_micro2': 'Has KPI micro output metrics',
    'kpioutput_macro1': 'No KPI macro output metrics',
    'kpioutput_macro2': 'Has KPI macro output metrics',
    
    # Outcome and effectiveness variables
    'p_effectiveness': 'Subjective Effectiveness of Program',
    'p_roi': 'ROI achieved',
    'roi_pos': 'Positive ROI (indicator)',
    'veff': 'Program effectiveness indicator',
    
    # Skills and training variables
    'sk_gap': 'Skill gap measure',
    'sk_gap_severe': 'Severe skill gap',
    'sk_gap_overall': 'Overall skill gap measure',
    'sk_gap_med': 'Medium skill gap',
    'sk_gap_sev': 'Severe skill gap indicator',
    'dum_sk_gap1': 'Skill gap level 0',
    'dum_sk_gap2': 'Skill gap level 1',
    'dum_sk_gap3': 'Skill gap level 2',
    'sk_miss': 'Missing skill data',
    'sk_gapcertainty': 'Skill gap: Certainty about gap',
    
    # Training skills
    'tr_sk_n_soft_leader': 'Leadership Skills - Included in Training',
    'tr_sk_n_soft_adapt': 'Adaptability and Flexibility - Included in Training',
    'tr_sk_n_man_comm': 'Communication Skills - Included in Training',
    'tr_sk_n_man_problemsolving': 'Problem-Solving Skills - Included in Training',
    'tr_sk_n_man_projectman': 'Project Management Skills - Included in Training',
    'tr_sk_n_f_industry': 'Industry-Specific Knowledge - Included in Training',
    'tr_sk_n_f_customer': 'Customer Service Skills - Included in Training',
    'tr_sk_n_f_marketing': 'Sales and Marketing Skills - Included in Training',
    'tr_sk_n_f_finance': 'Financial Management Skills - Included in Training',
    'tr_sk_n_f_hr': 'Human Resources Skills - Included in Training',
    'tr_sk_n_f_supplychain': 'Supply Chain and Logistics Skills - Included in Training',
    'tr_sk_n_dig_basic': 'Basic Digital Skills - Included in Training',
    'tr_sk_n_dig_advance': 'Advanced Digital Skills - Included in Training',
    'tr_sk_n_dig_prod': 'Production-Related Digital Skills - Included in Training',
    'tr_sk_n_dig_data': 'Data Analysis and Processing Skills - Included in Training',
    'tr_sk_n_career': 'Career Transition Skills - Included in Training',
    'tr_sk_n_other': 'Other Skills - Included in Training',
    'tr_part': 'Training participants',
    'tr_eligibility': 'Training eligibility',
    'tr_part_exp': 'Expected training participants',
    
    # Business rationale variables
    'reason_tech': 'New Technology',
    'reason_prodinn': 'New Products',
    'reason_bmodel': 'New Business Model',
    'reason_sust': 'New Sustainability Objectives',
    'reason_other': 'Other reason',
    'evp_attract': 'Attracting Talent',
    'evp_engage': 'Keeping Employees Engaged',
    'evp_retain': 'Retaining Employees',
    'evp_orgculture': 'Contributing to Learning Org Culture',
    'evp_diversity': 'Building a More Diverse Org',
    'reasongroup_evp': 'EVP Employee',
    'reasongroup_evpculture': 'EVP Culture',
    'ecp_promotion': 'Help Qualify for Internal Promotion Opportunities',
    'ecp_other': 'Other career path reason',
    'stat_dev_noexist': 'Help Develop Skills that Do not Exist in External Labor Market',
    'stat_dev_expensive': 'Help Develop Skills that are Too Expensive to Hire/Contract',
    'stat_evp': 'Strategic employee value proposition',
    'stat_retention': 'Strategic retention focus',
    'stat_diversity': 'Strategic diversity focus',
    
    # Program characteristics
    'plength_long': 'Program length is long indicator',
    'p_participated_coarse': 'Participation level (coarse)',
    'p_size_coarse1': 'Small participation size',
    'p_size_coarse2': 'Medium participation size',
    'p_size_coarse3': 'Large participation size',
    'pdur1': 'Program duration < 1 month',
    'pdur2': 'Program duration 2-6 months',
    'pdur3': 'Program duration 7-12 months',
    'pdur4': 'Program duration > 12 months',
    'phours1': 'Training hours < 10',
    'phours2': 'Training hours 10-49',
    'phours3': 'Training hours 50-99',
    'phours4': 'Training hours 100-199',
    'phours5': 'Training hours 200-499',
    'phours6': 'Training hours > 500',
    'pcomp1': 'Entirely compensated hours',
    'pcomp2': 'Partly compensated hours',
    'pcomp3': 'Uncompensated hours',
    'padv1': 'Advocate - Top Management',
    'padv2': 'Advocate - HR',
    'padv3': 'Advocate - BU and Middle Management',
    'padv4': 'Advocate - Employees and Others',
    'p_adv_top': 'Advocate is top management',
    'p_resp_top': 'Responsibility - top management',
    'p_resp_hr': 'Responsibility - HR',
    'p_adv_resp_match': 'Advocate and responsible match',
    'presp1': 'Responsibility - Top Management',
    'presp2': 'Responsibility - HR',
    'presp3': 'Responsibility - BU and Middle Management',
    'presp4': 'Responsibility - Employees and Others',
    'pdelivery1': 'Delivery - External Instructors only',
    'pdelivery2': 'Delivery - External and Internal',
    'pdelivery3': 'Delivery - Internal Instructers only',
    'pdelmix': 'Delivery mix indicator',
    'pmand1': 'Program is mandatory',
    'pmand2': 'Program is voluntary',
    'pmandatory': 'Program is mandatory indicator',
    'papp1': 'Anyone could apply regardless of function/department',
    'papp2': 'Anyone could apply if in specific function/department',
    'papp3': 'Only people nominated by managers',
    'papp4': 'Other application process',
    'pappall': 'Open application to all',
    'psel1': 'Selection process - Yes',
    'psel2': 'Selection process - No',
    'psel': 'Has selection process',
    'p_cri_individual': 'Individual criteria',
    'diff_man': 'Difference management indicator',
    'diff_emp': 'Difference employee indicator',
    'exppart1': 'Participation exceeded expectations',
    'exppart2': 'Participation met expectations',
    'exppart3': 'Participation below expectations',
    'expart_exc': 'Participation exceeded expectations indicator',
    'pcost1': 'Cost < $500',
    'pcost2': 'Cost $501-$1,000',
    'pcost3': 'Cost $1,001-$5,000',
    'pcost4': 'Cost $5,001-$10,000',
    'pcost5': 'Cost > $10,000',
    'pcost_high': 'High cost indicator',
    'stand1': 'Very standard across geographies',
    'stand3': 'Very flexible',
    'pilot1': 'No pilot',
    'pilot2': 'Pilot < 3 months',
    'pilot3': 'Pilot 3 months to 1 year',
    'pilot4': 'Pilot > 1 year',
    'nopilot': 'No pilot indicator',
    'control1': 'Control/treatment - Yes',
    'control2': 'Control/treatment - No',
    'assess1': 'Final assessment - Yes',
    'assess2': 'Final assessment - No',
    'above_median_kpi_tracked': 'Above median KPIs tracked',
    'above_median_kpi_tracked_freq': 'Above median KPI review frequency',
    
    # Type variables
    'type_dig': 'Digital focus type',
    'type_every': 'Comprehensive type',
    'type_soft': 'Soft skills focus type',
    'type_softind': 'Soft skills industry focus type',
    'type_nogap': 'No gap type',
    
    # Cluster variables
    'clus4': 'Cluster ID (4 clusters)',
    'cc1': 'Cluster 1 (4-cluster solution)',
    'cc2': 'Cluster 2 (4-cluster solution)',
    'cc3': 'Cluster 3 (4-cluster solution)',
    'cc4': 'Cluster 4 (4-cluster solution)',
    'clusplot': 'Cluster ID for plotting',
    'clus5': 'Cluster ID (5 clusters)',
    'alt_cc1': 'Alt Cluster 1 (5-cluster solution)',
    'alt_cc2': 'Alt Cluster 2 (5-cluster solution)',
    'alt_cc3': 'Alt Cluster 3 (5-cluster solution)',
    'alt_cc4': 'Alt Cluster 4 (5-cluster solution)',
    'alt_cc5': 'Alt Cluster 5 (5-cluster solution)',
    'clusplot2': 'Cluster ID for plotting (alternate)',
    'tr_clus4': 'Training Cluster ID',
    'tr_clusplot2': 'Training Cluster ID for plotting',
    'dd_clus1': 'Digital+Cognitive cluster',
    'dd_clus2': 'Everything cluster',
    'dd_clus3': 'Soft cluster',
    'dd_clus4': 'Digital+Soft cluster',
    'ee_clus1': 'Digital+Cognitive cluster (alt)',
    'ee_clus2': 'Everything cluster (alt)',
    'ee_clus3': 'Soft cluster (alt)',
    'ee_clus4': 'Digital+Soft cluster (alt)',
    
    # Hiring strategy variables
    'l_hire_notra': 'Hire without training',
    'l_hire_tra': 'Hire with training',
    'l_outsource': 'Outsource',
    'l_train': 'Train existing employees',
    'l_other': 'Other hiring strategy',
    'l_no': 'No hiring strategy',
    'lev_all': 'All levels',
    'num_checked': 'Number of checked items',
    'num_checked2': 'Number of checked items (alt)',
    'num_checked3': 'Number of checked items (alt2)',
    'hire_and_train': 'Hire and train strategy', 
    
    # Additional mappings based on graph outputs
    'p_year_end_clone2': 'Program End Year (Clone)',
    'inc_wrk_all_Non-financial_Incentive': 'Worker Incentive - Non-financial Incentive',
    'p_targetfunc_it_Selected': 'Target Function: IT selected',
    'p_targetfunc_op_Not_Selected': 'Target Function: Operations not selected',
    'p_targetfunc_accfin_Selected': 'Target Function: Accounting/Finance selected',
    'p_hourstrained_200_-_499_hours': 'Program Duration: 200-499 hours',
    'p_advocacy_HR_Leaders': 'Advocate: HR Leaders',
    'p_responsibility_HR_Leaders': 'Responsibility: HR Leaders',
    'dd_design_mm': 'Design - Middle Managers',
    'p_hours_long': 'Program with long hours',
    'p_roi_Negative_ROI': 'Program reports negative ROI'
}

# Program-specific variables
program_variables = [
    # Participation and timing
    'p_participated', 'p_participated_2023', 'p_mandavolunt', 'p_year_start', 'p_year_end', 
    'p_ongoing', 'p_program_length', 'p_hourstrained', 'p_duration', 
    
    # Program characteristics
    'p_comphours', 'p_otjactivities', 'p_cost', 'p_adequatefund', 'p_adequatefunddummy', 
    
    # Funding sources
    'p_fund_gov', 'p_fund_org', 'p_fund_wrk', 'p_fund_union', 'p_fund_other', 
    
    # Program structure
    'p_advocacy', 'p_advocacy_hier', 'p_responsibility', 'p_responsibility_hier', 
    'p_application', 'p_selection', 
    
    # Selection criteria
    'p_criteria_jobtitle', 'p_criteria_tenure', 'p_criteria_qualifications', 
    'p_criteria_assmskills', 'p_criteria_assmsmotivation', 'p_criteria_managerrec', 
    'p_criteria_other', 
    
    # Target groups
    'p_targetemp_c', 'p_targetemp_bul', 'p_targetemp_mm', 'p_targetemp_emp', 
    'p_targetfunc_leg', 'p_targetfunc_hr', 'p_targetfunc_adm', 'p_targetfunc_it', 
    'p_targetfunc_op', 'p_targetfunc_mrksal', 'p_targetfunc_rd', 'p_targetfunc_accfin', 
    'p_targetfunc_cust', 
    
    # Implementation
    'p_difloc', 'p_difstand', 'p_eligibility', 'p_part', 'p_part_exp', 
    
    # Design and pilot
    'dd_pilot_length', 'dd_pilot_dummy', 'dd_pilot_ct', 'dd_pilot_over', 
    'dd_design_board', 'dd_design_c', 'dd_design_hr', 'dd_design_bul', 'dd_design_mm', 
    'dd_design_emp', 'dd_design_union', 'dd_design_ia', 'dd_external', 
    
    # External design
    'dd_extdesign_ta', 'dd_extdesign_gov', 'dd_extdesign_acad', 'dd_extdesign_lsshelf', 
    'dd_extdesign_custom', 'dd_extdesign_all', 'dd_delivery', 
    
    # Motivation
    'mot_mgr', 'mot_wrk', 'mot_mgragg', 'mot_wrkagg', 
    
    # Incentives
    'inc_mgr_fin', 'inc_mgr_nofin', 'inc_mgr_rec', 'inc_mgr_intrin', 'inc_mgr_none', 
    'inc_mgr_all', 'inc_wrk_career', 'inc_wrk_risk', 'inc_wrk_fin', 'inc_wrk_nofin', 
    'inc_wrk_cert', 'inc_wrk_rec', 'inc_wrk_strat', 'inc_wrk_job', 'inc_wrk_all', 
    
    # Evaluation and tracking
    'exp_participation', 'p_finassessment', 'k_track_numberppl', 'k_track_hours', 
    'k_track_attract', 'k_track_completion', 'k_track_changeskill', 'k_track_changecareer', 
    'k_track_otherHR', 'k_track_busoutcomes', 'k_track_benefitstraining', 'k_track_other', 
    'k_track_none', 
    
    # Review process
    'k_review_BoD', 'k_review_c', 'k_review_hr', 'k_review_bul', 'k_review_mm', 
    'k_review_emp', 'k_review_union', 'k_review_ia', 'k_review_other', 
    'k_reviewcombined_c', 'k_reviewcombined_hr', 'k_reviewcombined_others', 'k_freq'
]

# Outcome variables to exclude
outcomes_to_exclude = [
    # Program continuation and investment
    'p_cont_investment',
    
    # Challenge variables
    'p_challenge_convincingemployees',
    'p_challenge_selecting',
    'p_challenge_progcompl',
    'p_challenge_learning',
    'p_challenge_newjob',
    'p_challenge_convmanager',
    'p_challenge_linkprogramcareer',
    'p_challenge_effectiveness',
    'p_challenge_scaling',
    'p_challenge_determreturn',
    'p_challenge_supportoutsideHR',
    'p_challenge_funding',
    'p_challenge_other',
    
    # Effectiveness and tracking
    'p_effectiveness',
    'k_track_hours'
]

def add_unique_keys(label_mapping, variable_labels):
    """
    Add unique keys to label_mapping that are in variable_labels but not in label_mapping
    """
    new_mapping = label_mapping.copy()
    for key in variable_labels:
        if key not in new_mapping and variable_labels[key] is not None and variable_labels[key].strip() != '':
            new_mapping[key] = variable_labels[key]
    return new_mapping